# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/wix/Documents/Coding/ETH Courses/PBS_project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/wix/Documents/Coding/ETH Courses/PBS_project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/wix/Documents/Coding/ETH Courses/PBS_project/CMakeFiles" "/Users/wix/Documents/Coding/ETH Courses/PBS_project/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/wix/Documents/Coding/ETH Courses/PBS_project/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PBS_project

# Build rule for target.
PBS_project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PBS_project
.PHONY : PBS_project

# fast build rule for target.
PBS_project/fast:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/build
.PHONY : PBS_project/fast

Basic_SPH_System.o: Basic_SPH_System.cpp.o

.PHONY : Basic_SPH_System.o

# target to build an object file
Basic_SPH_System.cpp.o:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/Basic_SPH_System.cpp.o
.PHONY : Basic_SPH_System.cpp.o

Basic_SPH_System.i: Basic_SPH_System.cpp.i

.PHONY : Basic_SPH_System.i

# target to preprocess a source file
Basic_SPH_System.cpp.i:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/Basic_SPH_System.cpp.i
.PHONY : Basic_SPH_System.cpp.i

Basic_SPH_System.s: Basic_SPH_System.cpp.s

.PHONY : Basic_SPH_System.s

# target to generate assembly for a file
Basic_SPH_System.cpp.s:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/Basic_SPH_System.cpp.s
.PHONY : Basic_SPH_System.cpp.s

Maya_Interface.o: Maya_Interface.cpp.o

.PHONY : Maya_Interface.o

# target to build an object file
Maya_Interface.cpp.o:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/Maya_Interface.cpp.o
.PHONY : Maya_Interface.cpp.o

Maya_Interface.i: Maya_Interface.cpp.i

.PHONY : Maya_Interface.i

# target to preprocess a source file
Maya_Interface.cpp.i:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/Maya_Interface.cpp.i
.PHONY : Maya_Interface.cpp.i

Maya_Interface.s: Maya_Interface.cpp.s

.PHONY : Maya_Interface.s

# target to generate assembly for a file
Maya_Interface.cpp.s:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/Maya_Interface.cpp.s
.PHONY : Maya_Interface.cpp.s

OpenGL_Renderer.o: OpenGL_Renderer.cpp.o

.PHONY : OpenGL_Renderer.o

# target to build an object file
OpenGL_Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/OpenGL_Renderer.cpp.o
.PHONY : OpenGL_Renderer.cpp.o

OpenGL_Renderer.i: OpenGL_Renderer.cpp.i

.PHONY : OpenGL_Renderer.i

# target to preprocess a source file
OpenGL_Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/OpenGL_Renderer.cpp.i
.PHONY : OpenGL_Renderer.cpp.i

OpenGL_Renderer.s: OpenGL_Renderer.cpp.s

.PHONY : OpenGL_Renderer.s

# target to generate assembly for a file
OpenGL_Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/OpenGL_Renderer.cpp.s
.PHONY : OpenGL_Renderer.cpp.s

PCI_SPH.o: PCI_SPH.cpp.o

.PHONY : PCI_SPH.o

# target to build an object file
PCI_SPH.cpp.o:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/PCI_SPH.cpp.o
.PHONY : PCI_SPH.cpp.o

PCI_SPH.i: PCI_SPH.cpp.i

.PHONY : PCI_SPH.i

# target to preprocess a source file
PCI_SPH.cpp.i:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/PCI_SPH.cpp.i
.PHONY : PCI_SPH.cpp.i

PCI_SPH.s: PCI_SPH.cpp.s

.PHONY : PCI_SPH.s

# target to generate assembly for a file
PCI_SPH.cpp.s:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/PCI_SPH.cpp.s
.PHONY : PCI_SPH.cpp.s

Particle_Generator.o: Particle_Generator.cpp.o

.PHONY : Particle_Generator.o

# target to build an object file
Particle_Generator.cpp.o:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/Particle_Generator.cpp.o
.PHONY : Particle_Generator.cpp.o

Particle_Generator.i: Particle_Generator.cpp.i

.PHONY : Particle_Generator.i

# target to preprocess a source file
Particle_Generator.cpp.i:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/Particle_Generator.cpp.i
.PHONY : Particle_Generator.cpp.i

Particle_Generator.s: Particle_Generator.cpp.s

.PHONY : Particle_Generator.s

# target to generate assembly for a file
Particle_Generator.cpp.s:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/Particle_Generator.cpp.s
.PHONY : Particle_Generator.cpp.s

Uniform_Grid.o: Uniform_Grid.cpp.o

.PHONY : Uniform_Grid.o

# target to build an object file
Uniform_Grid.cpp.o:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/Uniform_Grid.cpp.o
.PHONY : Uniform_Grid.cpp.o

Uniform_Grid.i: Uniform_Grid.cpp.i

.PHONY : Uniform_Grid.i

# target to preprocess a source file
Uniform_Grid.cpp.i:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/Uniform_Grid.cpp.i
.PHONY : Uniform_Grid.cpp.i

Uniform_Grid.s: Uniform_Grid.cpp.s

.PHONY : Uniform_Grid.s

# target to generate assembly for a file
Uniform_Grid.cpp.s:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/Uniform_Grid.cpp.s
.PHONY : Uniform_Grid.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/main.cpp.s
.PHONY : main.cpp.s

viridis.o: viridis.cpp.o

.PHONY : viridis.o

# target to build an object file
viridis.cpp.o:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/viridis.cpp.o
.PHONY : viridis.cpp.o

viridis.i: viridis.cpp.i

.PHONY : viridis.i

# target to preprocess a source file
viridis.cpp.i:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/viridis.cpp.i
.PHONY : viridis.cpp.i

viridis.s: viridis.cpp.s

.PHONY : viridis.s

# target to generate assembly for a file
viridis.cpp.s:
	$(MAKE) -f CMakeFiles/PBS_project.dir/build.make CMakeFiles/PBS_project.dir/viridis.cpp.s
.PHONY : viridis.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... PBS_project"
	@echo "... Basic_SPH_System.o"
	@echo "... Basic_SPH_System.i"
	@echo "... Basic_SPH_System.s"
	@echo "... Maya_Interface.o"
	@echo "... Maya_Interface.i"
	@echo "... Maya_Interface.s"
	@echo "... OpenGL_Renderer.o"
	@echo "... OpenGL_Renderer.i"
	@echo "... OpenGL_Renderer.s"
	@echo "... PCI_SPH.o"
	@echo "... PCI_SPH.i"
	@echo "... PCI_SPH.s"
	@echo "... Particle_Generator.o"
	@echo "... Particle_Generator.i"
	@echo "... Particle_Generator.s"
	@echo "... Uniform_Grid.o"
	@echo "... Uniform_Grid.i"
	@echo "... Uniform_Grid.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... viridis.o"
	@echo "... viridis.i"
	@echo "... viridis.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

